
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 06 20:16:11 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 49;
  public static final int CONST = 9;
  public static final int IFNULL = 21;
  public static final int SEMI = 42;
  public static final int LPAREN = 25;
  public static final int CONTINUE = 10;
  public static final int RPAREN = 40;
  public static final int INSTANCEOF = 23;
  public static final int GRE = 19;
  public static final int AND = 3;
  public static final int LS = 26;
  public static final int OR = 34;
  public static final int BOOL = 48;
  public static final int COMMA = 8;
  public static final int CLASS = 6;
  public static final int INC = 22;
  public static final int DIV = 12;
  public static final int NEXT = 33;
  public static final int ASSIGN = 4;
  public static final int IF = 20;
  public static final int DOT = 13;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int EQUAL = 15;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int ADD = 2;
  public static final int NUMBER = 47;
  public static final int MOD = 29;
  public static final int IDENT = 46;
  public static final int BREAK = 5;
  public static final int VOID = 44;
  public static final int FOREACH = 17;
  public static final int COLON = 7;
  public static final int LBRACE = 24;
  public static final int ELSE = 14;
  public static final int LSQUARE = 27;
  public static final int READ = 38;
  public static final int WHILE = 45;
  public static final int RSQUARE = 41;
  public static final int NEQUAL = 31;
  public static final int RBRACE = 37;
  public static final int PROG = 36;
  public static final int EXTENDS = 16;
  public static final int LEQ = 28;
  public static final int DEC = 11;
  public static final int SUB = 43;
  public static final int GR = 18;
  public static final int PRINT = 35;
}

