
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 02 23:59:19 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 50;
  public static final int CONST = 9;
  public static final int IFNULL = 22;
  public static final int SEMI = 43;
  public static final int LPAREN = 26;
  public static final int CONTINUE = 10;
  public static final int RPAREN = 41;
  public static final int INSTANCEOF = 24;
  public static final int GRE = 20;
  public static final int AND = 3;
  public static final int LS = 27;
  public static final int OR = 35;
  public static final int BOOL = 49;
  public static final int COMMA = 8;
  public static final int CLASS = 6;
  public static final int INC = 23;
  public static final int DIV = 12;
  public static final int NEXT = 34;
  public static final int ASSIGN = 4;
  public static final int IF = 21;
  public static final int DOT = 14;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int EQUAL = 16;
  public static final int NEW = 33;
  public static final int error = 1;
  public static final int MUL = 31;
  public static final int ADD = 2;
  public static final int NUMBER = 48;
  public static final int MOD = 30;
  public static final int IDENT = 47;
  public static final int BREAK = 5;
  public static final int VOID = 45;
  public static final int FOREACH = 18;
  public static final int COLON = 7;
  public static final int LBRACE = 25;
  public static final int ELSE = 15;
  public static final int LSQUARE = 28;
  public static final int READ = 39;
  public static final int WHILE = 46;
  public static final int RSQUARE = 42;
  public static final int NEQUAL = 32;
  public static final int RBRACE = 38;
  public static final int PROG = 37;
  public static final int EXTENDS = 17;
  public static final int LEQ = 29;
  public static final int DEC = 11;
  public static final int SUB = 44;
  public static final int GR = 19;
  public static final int PRINT = 36;
  public static final int DO = 13;
}

